// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR9latghZqQT8VhQbH9w8wc7lJRRc_SS4',
    appId: '1:403149260641:web:e8cf2c928755a2bfa8e720',
    messagingSenderId: '403149260641',
    projectId: 'productsapp-6ee2d',
    authDomain: 'productsapp-6ee2d.firebaseapp.com',
    databaseURL: 'https://productsapp-6ee2d-default-rtdb.firebaseio.com',
    storageBucket: 'productsapp-6ee2d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj4RwtApCW5oFy9MRoda0wDkn8_Rnld_8',
    appId: '1:403149260641:android:e92d74585a0b4359a8e720',
    messagingSenderId: '403149260641',
    projectId: 'productsapp-6ee2d',
    databaseURL: 'https://productsapp-6ee2d-default-rtdb.firebaseio.com',
    storageBucket: 'productsapp-6ee2d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmqWftRl44pQg09P7NOKCHhcgIuLzLhSs',
    appId: '1:403149260641:ios:145cb258af001a43a8e720',
    messagingSenderId: '403149260641',
    projectId: 'productsapp-6ee2d',
    databaseURL: 'https://productsapp-6ee2d-default-rtdb.firebaseio.com',
    storageBucket: 'productsapp-6ee2d.appspot.com',
    iosClientId: '403149260641-f8qsks6j3n6o0uf0q8iqosip481u96jq.apps.googleusercontent.com',
    iosBundleId: 'com.example.productsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmqWftRl44pQg09P7NOKCHhcgIuLzLhSs',
    appId: '1:403149260641:ios:bad008d8fed49591a8e720',
    messagingSenderId: '403149260641',
    projectId: 'productsapp-6ee2d',
    databaseURL: 'https://productsapp-6ee2d-default-rtdb.firebaseio.com',
    storageBucket: 'productsapp-6ee2d.appspot.com',
    iosClientId: '403149260641-nii76gn96p36fkpscpt6fb1pl46egd92.apps.googleusercontent.com',
    iosBundleId: 'com.example.productsApp.RunnerTests',
  );
}
